### ISSUE TITLE
Could you add tag "openbb" to project?

### ISSUE THREAD

**Issue by DidierRLopes** [dMLTquant/openbb_sdk_exporation#6]
I am trying to compile all OpenBB open source projects that our community have put together in the same place.

https://github.com/search?q=topic:openbb&type=Repositories&l=&l=

![image](https://user-images.githubusercontent.com/25267873/214743805-7488cc41-cbce-44a7-b929-de1b6558ca21.png)

**Comment by dMLTquant** [comment]
Done. I have added several topics this repo, one of them is `openbb`

**Comment by DidierRLopes** [comment]
Going to be announced soon 👀

<img width="1101" alt="Screen Shot 2023-01-27 at 10 37 44 AM" src="https://user-images.githubusercontent.com/25267873/215167832-0cebefe8-663e-41c7-8422-92ddeee3171d.png">

You may also want a description of what this project is about!

**Comment by dMLTquant** [comment]
> Going to be announced soon 👀
> 
> <img alt="Screen Shot 2023-01-27 at 10 37 44 AM" width="1101" src="https://user-images.githubusercontent.com/25267873/215167832-0cebefe8-663e-41c7-8422-92ddeee3171d.png">
> 
> You may also want a description of what this project is about!

@DidierRLopes that makes a lot of sense👍 Thank you for pointing out my laziness 😳 in not fully and correctly settling out this project 😉

**Comment by DidierRLopes** [comment]
Thank you, and any feedback please let me know and am happy to help 🙏🏽
